### ISSUE TITLE
Mountable web endpoint:  Rails only?

### ISSUE THREAD

**Issue by findchris** [danmayer/coverband#167]
Hi there.

I've got coverband running and when I `rake coverband:coverage`, a browser tab opens with the word "loading" and a broken image.  Viewing the source, I can see it's trying to fetch `application.js` and `application.css`, so I wonder if these web endpoint is a Rails-only option?  I'm not running Rails (it's a simple Rack app), and I'd like to view the coverage stats.  What am I missing?

Thanks for clarifying.

**Comment by kbaum** [comment]
Just tried this out on my own and verified that this is indeed a problem. This was actually a great exercise as it uncovered what i think are additional problems. I created an empty directory with just a Rakefile containing:

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'coverband'
end

require 'coverband'
require 'coverband/utils/tasks'
```
When I execute `rake coverband:coverage`, I get:

```
➜  coverband_test git:(aaa3af4) ✗ rake coverband:coverage
rake aborted!
LoadError: cannot load such file -- rack
/Users/karlbaum/.gem/ruby/2.5.3/gems/coverband-4.0.1/lib/coverband/reporters/web.rb:3:in `require'
/Users/karlbaum/.gem/ruby/2.5.3/gems/coverband-4.0.1/lib/coverband/reporters/web.rb:3:in `<top (required)>'
/Users/karlbaum/.gem/ruby/2.5.3/gems/coverband-4.0.1/lib/coverband.rb:25:in `require'
/Users/karlbaum/.gem/ruby/2.5.3/gems/coverband-4.0.1/lib/coverband.rb:25:in `<top (required)>'
/Users/karlbaum/.gem/ruby/2.5.3/gems/bundler-1.17.1/lib/bundler/runtime.rb:81:in `require'
/Users/karlbaum/.gem/ruby/2.5.3/gems/bundler-1.17.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/Users/karlbaum/.gem/ruby/2.5.3/gems/bundler-1.17.1/lib/bundler/runtime.rb:76:in `each'
/Users/karlbaum/.gem/ruby/2.5.3/gems/bundler-1.17.1/lib/bundler/runtime.rb:76:in `block in require'
/Users/karlbaum/.gem/ruby/2.5.3/gems/bundler-1.17.1/lib/bundler/runtime.rb:65:in `each'
/Users/karlbaum/.gem/ruby/2.5.3/gems/bundler-1.17.1/lib/bundler/runtime.rb:65:in `require'
/Users/karlbaum/.gem/ruby/2.5.3/gems/bundler-1.17.1/lib/bundler/inline.rb:70:in `gemfile'
/Users/karlbaum/workspace/coverband_test/Rakefile:3:in `<top (required)>'
/Users/karlbaum/.gem/ruby/2.5.3/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
```
So added rack to the gemfile block:

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'coverband'
  gem 'rack'
end

require 'coverband'
require 'coverband/utils/tasks'
```

Then I got:

```
➜  coverband_test git:(aaa3af4) ✗ rake coverband:coverage
D, [2019-01-17T21:19:43.637862 #93373] DEBUG -- : using default configuration
D, [2019-01-17T21:19:43.638361 #93373] DEBUG -- : Coverband: Starting background reporting
D, [2019-01-17T21:19:43.638875 #93373] DEBUG -- : using default configuration
rake aborted!
Don't know how to build task 'environment' (See the list of available tasks with `rake --tasks`)
/Users/karlbaum/.gem/ruby/2.5.3/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => coverband:coverage
(See full trace by running task with --trace)
D, [2019-01-17T21:19:43.641810 #93373] DEBUG -- : Coverband: Reported coverage before exit
```

So I defined an environment task:

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'coverband'
  gem 'rack'
end

require 'coverband'
require 'coverband/utils/tasks'

task :environment do
end
```

Only then do i now have the broken report with just loading.

**Comment by findchris** [comment]
Thanks for chiming in @kbaum - glad you could verify.  It seems there is an assumption of a Rails app being present to view the endpoint, which doesn't seem to be a hard requirement from the docs, so just trying to figure out how to view the report.

**Comment by danmayer** [comment]
hmm the broken loading and such is new and came from moving away from the simplecov dependency. So it isn't that you need Rails, but that we broke local file views while porting into Coverband. It should be writing all the assets needed with the rake task to the `./coverage` the directory the same way that simple_cov did...

So this is a bug / regression, which we should be able to fix in the next release.

A quick fix or workaround would be to copy the public files to that directory yourself basically this directory https://github.com/danmayer/coverband/tree/master/public into your `./coverage` directory

**Comment by kbaum** [comment]
Quick question on this. I did verify the `rake coverband:coverage` is working on my rails project with 4.01. Given the missing assets, shouldn't it just be broken everywhere?

**Comment by kbaum** [comment]
Re-opening this for now since it's a bug.
